on: [push, pull_request]

jobs:
  push_gpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    # Authenticates packages to push to GPR
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
        source-url: https://nuget.pkg.github.com/brawrdon/index.json  
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Create the package
      run: dotnet pack --configuration Release src/Pyxcell.csproj
    - name: Publish to Github Package Repository
      run: dotnet nuget push src/bin/Release/*.nupkg --skip-duplicate
  
  push_nuget_org:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    # Authenticates packages to push to GPR
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
    - name: Create the package
      run: dotnet pack --configuration Release src/Pyxcell.csproj
    - name: Publish to NuGet Gallery
      run: dotnet nuget push src/bin/Release/*.nupkg --skip-duplicate
