name: Test & Package
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install Dependencies
      run: dotnet restore
    - name: Build Project
      run: dotnet build
    - name: Copy Resources
      run: cp ./tests/Resources/* ./tests/bin/Debug/netcoreapp3.1/
    - name: Run Tests
      working-directory: ./tests/
      run: dotnet test --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      if: startsWith(github.ref, 'refs/tags/v')
    - name: Upload Test Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true

  package:
    name: Package & Upload
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    # Authenticates packages to push to GPR
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101' # SDK Version to use.
        source-url: https://nuget.pkg.github.com/brawrdon/index.json  
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Package
      run: dotnet pack --configuration Release src/Pyxcell.csproj
    - name: Publish to Github Package Repository
      run: dotnet nuget push src/bin/Release/*.nupkg
    - name: Publish to NuGet Gallery
      run: dotnet nuget push src/bin/Release/*.nupkg --api-key ${{secrets.NUGET_DEPLOY_KEY}} --source https://api.nuget.org/v3/index.json
