on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    # Authenticates packages to push to GPR
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
        source-url: https://nuget.pkg.github.com/brawrdon/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Create the package
      run: dotnet pack --configuration Release src/Pxycell.csproj
    - name: Publish the package to GPR
      run: dotnet nuget push src/bin/Release/*.nupkg
